trigger:
- main

pool:
  name: azurevm  # self-hosted agent pool

stages:
- stage: script
  displayName: "Executing commands"
  jobs:
  - job: script
    displayName: "Executing script"
    steps:
    - script: |
        az --version
        sudo apt-get update -y
        sudo apt-get install git -y
      displayName: "Run commands"

- stage: BuildAndPush
  displayName: "Build and push Docker image"
  jobs:
  - job: BuildAndPushJob
    displayName: "Build and push Docker image"
    steps:
    - task: Docker@2
      displayName: "Build and push image"
      inputs:
        containerRegistry: 'amani-serconn'   # Docker Registry/Azure Container Registry service connection
        repository: 'thirdimage'             # Repo name inside ACR (e.g. amaniacr.azurecr.io/thirdimage)
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        buildContext: '.'                    # Recommended to set explicitly
        tags: |
          $(Build.BuildNumber)
          latest


