export const FLUSH_DB_DATA = "FLUSH_DB_DATA";
export const FLUSH_DB_SUCCESS = "FLUSH_DB_SUCCESS";
export const FLUSH_DB_FAILURE = "FLUSH_DB_FAILURE";

export const CONTAINER_RESTART_DATA = 'CONTAINER_RESTART_DATA';
export const CONTAINER_RESTART_SUCCESS = 'CONTAINER_RESTART_SUCCESS';
export const CONTAINER_RESTART_FAILURE = 'CONTAINER_RESTART_FAILURE';
