export const ADD_AI_DOCUMENT_DATA = 'ADD_AI_DOCUMENT_DATA';
export const ADD_AI_DOCUMENT_SUCCESS = 'ADD_AI_DOCUMENT_SUCCESS';
export const ADD_AI_DOCUMENT_FAILURE = 'ADD_AI_DOCUMENT_FAILURE';

// aiTestCasesActionTypes.js
export const ADD_AI_CSV_DATA = "ADD_AI_CSV_DATA";
export const ADD_AI_CSV_SUCCESS = "ADD_AI_CSV_SUCCESS";
export const ADD_AI_CSV_FAILURE = "ADD_AI_CSV_FAILURE";
