export const GIT_RELEASE_NOTE_DATA = 'GIT_RELEASE_NOTE_DATA';
export const GIT_RELEASE_NOTE_SUCCESS = 'GIT_RELEASE_NOTE_SUCCESS';
export const GIT_RELEASE_NOTE_FAILURE = 'GIT_RELEASE_NOTE_FAILURE';

export const GIT_RELEASE_FEEDBACK_DATA ='GIT_RELEASE_FEEDBACK_DATA';
export const GIT_RELEASE_FEEDBACK_SUCCESS ='GIT_RELEASE_FEEDBACK_SUCCESS';
export const GIT_RELEASE_FEEDBACK_FAILURE ='GIT_RELEASE_FEEDBACK_DATA';

export const GIT_COMMIT_FEEDBACK_DATA ='GIT_COMMIT_FEEDBACK_DATA';
export const GIT_COMMIT_FEEDBACK_FAILURE = 'GIT_COMMIT_FEEDBACK_FAILURE';
export const GIT_COMMIT_FEEDBACK_SUCCESS ='GIT_COMMIT_FEEDBACK_SECCESS';