export const ADD_INGESTION_DATA = 'ADD_INGESTION_DATA';
export const ADD_INGESTION_SUCCESS = 'ADD_INGESTION_SUCCESS';
export const ADD_INGESTION_FAILURE = 'ADD_INGESTION_FAILURE';
export const INGETSED_REPO_DATA ='INGETSED_REPO_DATA';
export const INGESTED_REPO_SUCCESS ='INGESTED_REPO_SUCCESS';
export const INGESTED_REPO_FAILURE = 'INGESTED_REPO_FAILURE'