export const ADD_INGESTION_DATA = 'ADD_INGESTION_DATA';
export const ADD_INGESTION_SUCCESS = 'ADD_INGESTION_SUCCESS';
export const ADD_INGESTION_FAILURE = 'ADD_INGESTION_FAILURE';
export const INGESTION_STAUS ='INGESTION_STATUS';
export const INGESTION_SUCCESS = 'INGESTION_SUCCESS';
export const INGESTION_FAILURE =' INGESTION_FAILURE'
