export const FETCH_ANSWERS_SUCCESS = 'FETCH_ANSWERS_SUCCESS';
export const FETCH_ANSWERS_FAILURE = 'FETCH_ANSWERS_FAILURE';
export const FETCH_ANSWERS_DATA = 'FETCH_ANSWERS_DATA';

export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
